### ISSUE TITLE
QuickAlert.cancel() must have been added since day 1

### ISSUE THREAD

**Issue by Mu7ammadRasul** [belovance/QuickAlert#14]
i'm navigating a user into another page in which when i get back to the main page the dialog is still existing which is super annoying.

there should have been a 'cancelation' to fix the issue, note that i tried `Navigator.pop()` but it crushes the app.

**Comment by ItsAkashS22** [comment]
Hello @Mu7ammadRasul 👋

You can achieve this with 2 ways,
1. Pop the dialog 1st and then push to new page.
```dart
QuicklAlert.show(...).whenCompleted((){
  Navigator.push(...);
});
```

2. Push a new page 1st and on return back pop the dialog.
```dart
QuicklAlert.show(
  onConfirmBtnTap: () {
    Navigator.push(...).whenCompleted((){
      Navigator.pop();
    });
  },
);
```
I hope this solves the issue, this package is built for very easy usage so that even the beginners can understand, hence advanced options or controllers are not implemented.
Happy Coding ✨
